# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{commons-fileupload}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Cooper - martinc@apache.org", "dIon Gillard - dion@apache.org", "Jason van Zyl - jason@zenplex.com", "Robert Burrell Donkin - rdonkin@apache.org", "Jochen Wiedmann - jochen.wiedmann@gmail.com", "Daniel Rall - dlr@finemaltcoding.com", "Sean C. Sullivan - sean |at| seansullivan |dot| com", "John McNally - jmcnally@collab.net"]
  s.date = %q{2009-11-22}
  s.description = %q{The FileUpload component provides a simple yet flexible means of adding support for multipart
    file upload functionality to servlets and web applications.}
  s.email = %q{autobuild@javagems.org}
  s.homepage = %q{http://www.javagems.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A JavaGem version of Commons FileUpload - packaged by JavaGems (http://www.javagems.org) - original by The Apache Software Foundation (http://www.apache.org/)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<junit>, ["~> 3.8.2"])
    else
      s.add_dependency(%q<junit>, ["~> 3.8.2"])
    end
  else
    s.add_dependency(%q<junit>, ["~> 3.8.2"])
  end
end

